### ISSUE TITLE
Handling top output missing date data differently

### ISSUE THREAD

**Issue by csutherl** [engineersamuel/javahighcpu#4]
What if the first line of your top output is missing the date, such as:

```
top - 05:47:49 up 12 days,  4:08,  6 users,  load average: 2.29, 2.16, 2.10
```

Why not grab the date/TZ info from the jstack dump and then grep out the time from above and fill it in? It could print a warning like 'we didnt have a date, so we created one for you based on other data' so that users know, but work around the missing date by using what top generates to prevent an error.

**Comment by engineersamuel** [comment]
Closing this out as the scripts to generate the output should always have the date.   I'd definitely entertain something like this if we get enough usage where people aren't or don't want to use the scripts, we can always re-open.
